#!/bin/bash

LOGDIR="./var/log"
NGINX_PID="$LOGDIR/pid.nginx"
GUNICORN_PID="$LOGDIR/pid.gunicorn"

print_status() {
    if [ $? -eq 0 ]; then
        echo "OK"
    else
        echo "FAIL"
    fi
}

delete_file() {
    [ -f $1 ] && rm -f $1
}

kill_program() {
    ps -ax | grep $1 | awk '{print $1}' | sed '$d' | xargs -r kill 2>/dev/null
}

mkdir -p $LOGDIR

if [ "$1" = "start" ]; then
    if [ ! -f $NGINX_PID ]; then
        echo -ne "Starting nginx..."
        nginx -c nginx.conf -p .
        print_status
    else
        echo "nginx is already running"
    fi

    if [ ! -f $GUNICORN_PID ]; then
        echo -ne "Starting gunicorn..."
        python3 app.py serve --gunicorn_args --access-logfile $LOGDIR/http.access.log.gunicorn --error-logfile $LOGDIR/http.error.log.gunicorn --pid $GUNICORN_PID --timeout 600 --reload &
        print_status
    else
        echo "gunicorn is already running"
    fi
else
    if [ -f $NGINX_PID ]; then
        echo -ne "Stopping nginx..."
        nginx -c nginx.conf -p . -s stop
        print_status
        delete_file $NGINX_PID
    else
        echo "nginx is not running"
    fi
    kill_program nginx

    if [ -f $GUNICORN_PID ]; then
        echo -ne "Stopping gunicorn..."
        kill -9 $(cat $GUNICORN_PID)
        print_status
        delete_file $GUNICORN_PID
    else
        echo "gunicorn is not running"
    fi
    kill_program gunicorn
fi
